version: '3'
services:
  web-server:
    image: hw11
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=hw11
      - POSTGRES_USER=kacang
      - POSTGRES_PASSWORD=kacang
